SELECT A_DATA.ANIMAL_ID, A_DATA.NAME
FROM ANIMAL_INS AS A_DATA
LEFT JOIN (SELECT *
           FROM ANIMAL_OUTS) AS B_DATA
           ON A_DATA.ANIMAL_ID = B_DATA.ANIMAL_ID
WHERE A_DATA.DATETIME > B_DATA.DATETIME
ORDER BY A_DATA.DATETIME ASC